package com.example.harkkatylogin;

public class Team {
    private String name;
    private TeamOtherStats otherStats;
    private TeamAllStats allStats;
    private Team5on5Stats _5_on_5_Stats;
    private Team4on5Stats _4_on_5_Stats;
    private Team5on4Stats _5_on_4_Stats;
    public Team(String name, String newName, String[] otherDataArr, String[] allDataArr,
                String[] _5_on_5_DataArr, String[] _4_on_5_DataArr, String[] _5_on_4_DataArr) {

        this.name =newName;


        otherStats=new TeamOtherStats(Integer.parseInt(otherDataArr[6]), Float.parseFloat(otherDataArr[7]),
                Float.parseFloat(otherDataArr[8]), Float.parseFloat(otherDataArr[9]),
                Float.parseFloat(otherDataArr[10]), Float.parseFloat(otherDataArr[11]),
                Float.parseFloat(otherDataArr[12]), Float.parseFloat(otherDataArr[13]),
                Float.parseFloat(otherDataArr[14]), Float.parseFloat(otherDataArr[15]),
                Float.parseFloat(otherDataArr[16]), Float.parseFloat(otherDataArr[17]),
                Float.parseFloat(otherDataArr[18]), Float.parseFloat(otherDataArr[19]),
                Float.parseFloat(otherDataArr[20]), Float.parseFloat(otherDataArr[21]),
                Float.parseFloat(otherDataArr[22]), Float.parseFloat(otherDataArr[23]),
                Float.parseFloat(otherDataArr[24]), Float.parseFloat(otherDataArr[25]),
                Float.parseFloat(otherDataArr[26]), Float.parseFloat(otherDataArr[27]),
                Float.parseFloat(otherDataArr[28]), Float.parseFloat(otherDataArr[29]),
                Float.parseFloat(otherDataArr[30]), Float.parseFloat(otherDataArr[31]),
                Float.parseFloat(otherDataArr[32]), Float.parseFloat(otherDataArr[33]),
                Float.parseFloat(otherDataArr[34]), Float.parseFloat(otherDataArr[35]),
                Float.parseFloat(otherDataArr[36]), Float.parseFloat(otherDataArr[37]),
                Float.parseFloat(otherDataArr[38]), Float.parseFloat(otherDataArr[39]),
                Float.parseFloat(otherDataArr[40]), Float.parseFloat(otherDataArr[41]),
                Float.parseFloat(otherDataArr[42]), Float.parseFloat(otherDataArr[43]),
                Float.parseFloat(otherDataArr[44]), Float.parseFloat(otherDataArr[45]),
                Float.parseFloat(otherDataArr[46]), Float.parseFloat(otherDataArr[47]),
                Float.parseFloat(otherDataArr[48]), Float.parseFloat(otherDataArr[49]),
                Float.parseFloat(otherDataArr[50]), Float.parseFloat(otherDataArr[51]),
                Float.parseFloat(otherDataArr[52]), Float.parseFloat(otherDataArr[53]),
                Float.parseFloat(otherDataArr[54]), Float.parseFloat(otherDataArr[55]),
                Float.parseFloat(otherDataArr[56]), Float.parseFloat(otherDataArr[57]),
                Float.parseFloat(otherDataArr[58]), Float.parseFloat(otherDataArr[59]),
                Float.parseFloat(otherDataArr[60]), Float.parseFloat(otherDataArr[61]),
                Float.parseFloat(otherDataArr[62]), Float.parseFloat(otherDataArr[63]),
                Float.parseFloat(otherDataArr[64]), Float.parseFloat(otherDataArr[65]),
                Float.parseFloat(otherDataArr[66]), Float.parseFloat(otherDataArr[67]),
                Float.parseFloat(otherDataArr[68]), Float.parseFloat(otherDataArr[69]),
                Float.parseFloat(otherDataArr[70]), Float.parseFloat(otherDataArr[71]),
                Float.parseFloat(otherDataArr[72]), Float.parseFloat(otherDataArr[73]),
                Float.parseFloat(otherDataArr[74]), Float.parseFloat(otherDataArr[75]),
                Float.parseFloat(otherDataArr[76]), Float.parseFloat(otherDataArr[77]),
                Float.parseFloat(otherDataArr[78]), Float.parseFloat(otherDataArr[79]),
                Float.parseFloat(otherDataArr[80]), Float.parseFloat(otherDataArr[81]),
                Float.parseFloat(otherDataArr[82]), Float.parseFloat(otherDataArr[83]),
                Float.parseFloat(otherDataArr[84]), Float.parseFloat(otherDataArr[85]),
                Float.parseFloat(otherDataArr[86]), Float.parseFloat(otherDataArr[87]),
                Float.parseFloat(otherDataArr[88]), Float.parseFloat(otherDataArr[89]),
                Float.parseFloat(otherDataArr[90]), Float.parseFloat(otherDataArr[91]),
                Float.parseFloat(otherDataArr[92]), Float.parseFloat(otherDataArr[93]),
                Float.parseFloat(otherDataArr[94]), Float.parseFloat(otherDataArr[95]),
                Float.parseFloat(otherDataArr[96]), Float.parseFloat(otherDataArr[97]),
                Float.parseFloat(otherDataArr[98]), Float.parseFloat(otherDataArr[99]),
                Float.parseFloat(otherDataArr[100]), Float.parseFloat(otherDataArr[101]),
                Float.parseFloat(otherDataArr[102]), Float.parseFloat(otherDataArr[103]),
                Float.parseFloat(otherDataArr[104]), Float.parseFloat(otherDataArr[105]),
                Float.parseFloat(otherDataArr[106]));




        allStats = new TeamAllStats(Integer.parseInt(allDataArr[6]),Float.parseFloat(allDataArr[7]),
                Float.parseFloat(allDataArr[8]),Float.parseFloat(allDataArr[9]),
                Float.parseFloat(allDataArr[10]),Float.parseFloat(allDataArr[11]),
                Float.parseFloat(allDataArr[12]),Float.parseFloat(allDataArr[13]),
                Float.parseFloat(allDataArr[14]),Float.parseFloat(allDataArr[15]),
                Float.parseFloat(allDataArr[16]),Float.parseFloat(allDataArr[17]),
                Float.parseFloat(allDataArr[18]),Float.parseFloat(allDataArr[19]),
                Float.parseFloat(allDataArr[20]),Float.parseFloat(allDataArr[21]),
                Float.parseFloat(allDataArr[22]),Float.parseFloat(allDataArr[23]),
                Float.parseFloat(allDataArr[24]),Float.parseFloat(allDataArr[25]),
                Float.parseFloat(allDataArr[26]),Float.parseFloat(allDataArr[27]),
                Float.parseFloat(allDataArr[28]),Float.parseFloat(allDataArr[29]),
                Float.parseFloat(allDataArr[30]),Float.parseFloat(allDataArr[31]),
                Float.parseFloat(allDataArr[32]),Float.parseFloat(allDataArr[33]),
                Float.parseFloat(allDataArr[34]),Float.parseFloat(allDataArr[35]),
                Float.parseFloat(allDataArr[36]),Float.parseFloat(allDataArr[37]),
                Float.parseFloat(allDataArr[38]),Float.parseFloat(allDataArr[39]),
                Float.parseFloat(allDataArr[40]),Float.parseFloat(allDataArr[41]),
                Float.parseFloat(allDataArr[42]),Float.parseFloat(allDataArr[43]),
                Float.parseFloat(allDataArr[44]),Float.parseFloat(allDataArr[45]),
                Float.parseFloat(allDataArr[46]),Float.parseFloat(allDataArr[47]),
                Float.parseFloat(allDataArr[48]),Float.parseFloat(allDataArr[49]),
                Float.parseFloat(allDataArr[50]),Float.parseFloat(allDataArr[51]),
                Float.parseFloat(allDataArr[52]),Float.parseFloat(allDataArr[53]),
                Float.parseFloat(allDataArr[54]),Float.parseFloat(allDataArr[55]),
                Float.parseFloat(allDataArr[56]),Float.parseFloat(allDataArr[57]),
                Float.parseFloat(allDataArr[58]),Float.parseFloat(allDataArr[59]),
                Float.parseFloat(allDataArr[60]),Float.parseFloat(allDataArr[61]),
                Float.parseFloat(allDataArr[62]),Float.parseFloat(allDataArr[63]),
                Float.parseFloat(allDataArr[64]),Float.parseFloat(allDataArr[65]),
                Float.parseFloat(allDataArr[66]),Float.parseFloat(allDataArr[67]),
                Float.parseFloat(allDataArr[68]),Float.parseFloat(allDataArr[69]),
                Float.parseFloat(allDataArr[70]),Float.parseFloat(allDataArr[71]),
                Float.parseFloat(allDataArr[72]),Float.parseFloat(allDataArr[73]),
                Float.parseFloat(allDataArr[74]),Float.parseFloat(allDataArr[75]),
                Float.parseFloat(allDataArr[76]),Float.parseFloat(allDataArr[77]),
                Float.parseFloat(allDataArr[78]),Float.parseFloat(allDataArr[79]),
                Float.parseFloat(allDataArr[80]),Float.parseFloat(allDataArr[81]),
                Float.parseFloat(allDataArr[82]),Float.parseFloat(allDataArr[83]),
                Float.parseFloat(allDataArr[84]),Float.parseFloat(allDataArr[85]),
                Float.parseFloat(allDataArr[86]),Float.parseFloat(allDataArr[87]),
                Float.parseFloat(allDataArr[88]),Float.parseFloat(allDataArr[89]),
                Float.parseFloat(allDataArr[90]),Float.parseFloat(allDataArr[91]),
                Float.parseFloat(allDataArr[92]),Float.parseFloat(allDataArr[93]),
                Float.parseFloat(allDataArr[94]),Float.parseFloat(allDataArr[95]),
                Float.parseFloat(allDataArr[96]),Float.parseFloat(allDataArr[97]),
                Float.parseFloat(allDataArr[98]),Float.parseFloat(allDataArr[99]),
                Float.parseFloat(allDataArr[100]),Float.parseFloat(allDataArr[101]),
                Float.parseFloat(allDataArr[102]),Float.parseFloat(allDataArr[103]),
                Float.parseFloat(allDataArr[104]),Float.parseFloat(allDataArr[105]),
                Float.parseFloat(allDataArr[106]));

        _5_on_5_Stats=new Team5on5Stats(Integer.parseInt(_5_on_5_DataArr[6]),Float.parseFloat(_5_on_5_DataArr[7]),
                Float.parseFloat(_5_on_5_DataArr[8]),Float.parseFloat(_5_on_5_DataArr[9]),
                Float.parseFloat(_5_on_5_DataArr[10]),Float.parseFloat(_5_on_5_DataArr[11]),
                Float.parseFloat(_5_on_5_DataArr[12]),Float.parseFloat(_5_on_5_DataArr[13]),
                Float.parseFloat(_5_on_5_DataArr[14]),Float.parseFloat(_5_on_5_DataArr[15]),
                Float.parseFloat(_5_on_5_DataArr[16]),Float.parseFloat(_5_on_5_DataArr[17]),
                Float.parseFloat(_5_on_5_DataArr[18]),Float.parseFloat(_5_on_5_DataArr[19]),
                Float.parseFloat(_5_on_5_DataArr[20]),Float.parseFloat(_5_on_5_DataArr[21]),
                Float.parseFloat(_5_on_5_DataArr[22]),Float.parseFloat(_5_on_5_DataArr[23]),
                Float.parseFloat(_5_on_5_DataArr[24]),Float.parseFloat(_5_on_5_DataArr[25]),
                Float.parseFloat(_5_on_5_DataArr[26]),Float.parseFloat(_5_on_5_DataArr[27]),
                Float.parseFloat(_5_on_5_DataArr[28]),Float.parseFloat(_5_on_5_DataArr[29]),
                Float.parseFloat(_5_on_5_DataArr[30]),Float.parseFloat(_5_on_5_DataArr[31]),
                Float.parseFloat(_5_on_5_DataArr[32]),Float.parseFloat(_5_on_5_DataArr[33]),
                Float.parseFloat(_5_on_5_DataArr[34]),Float.parseFloat(_5_on_5_DataArr[35]),
                Float.parseFloat(_5_on_5_DataArr[36]),Float.parseFloat(_5_on_5_DataArr[37]),
                Float.parseFloat(_5_on_5_DataArr[38]),Float.parseFloat(_5_on_5_DataArr[39]),
                Float.parseFloat(_5_on_5_DataArr[40]),Float.parseFloat(_5_on_5_DataArr[41]),
                Float.parseFloat(_5_on_5_DataArr[42]),Float.parseFloat(_5_on_5_DataArr[43]),
                Float.parseFloat(_5_on_5_DataArr[44]),Float.parseFloat(_5_on_5_DataArr[45]),
                Float.parseFloat(_5_on_5_DataArr[46]),Float.parseFloat(_5_on_5_DataArr[47]),
                Float.parseFloat(_5_on_5_DataArr[48]),Float.parseFloat(_5_on_5_DataArr[49]),
                Float.parseFloat(_5_on_5_DataArr[50]),Float.parseFloat(_5_on_5_DataArr[51]),
                Float.parseFloat(_5_on_5_DataArr[52]),Float.parseFloat(_5_on_5_DataArr[53]),
                Float.parseFloat(_5_on_5_DataArr[54]),Float.parseFloat(_5_on_5_DataArr[55]),
                Float.parseFloat(_5_on_5_DataArr[56]),Float.parseFloat(_5_on_5_DataArr[57]),
                Float.parseFloat(_5_on_5_DataArr[58]),Float.parseFloat(_5_on_5_DataArr[59]),
                Float.parseFloat(_5_on_5_DataArr[60]),Float.parseFloat(_5_on_5_DataArr[61]),
                Float.parseFloat(_5_on_5_DataArr[62]),Float.parseFloat(_5_on_5_DataArr[63]),
                Float.parseFloat(_5_on_5_DataArr[64]),Float.parseFloat(_5_on_5_DataArr[65]),
                Float.parseFloat(_5_on_5_DataArr[66]),Float.parseFloat(_5_on_5_DataArr[67]),
                Float.parseFloat(_5_on_5_DataArr[68]),Float.parseFloat(_5_on_5_DataArr[69]),
                Float.parseFloat(_5_on_5_DataArr[70]),Float.parseFloat(_5_on_5_DataArr[71]),
                Float.parseFloat(_5_on_5_DataArr[72]),Float.parseFloat(_5_on_5_DataArr[73]),
                Float.parseFloat(_5_on_5_DataArr[74]),Float.parseFloat(_5_on_5_DataArr[75]),
                Float.parseFloat(_5_on_5_DataArr[76]),Float.parseFloat(_5_on_5_DataArr[77]),
                Float.parseFloat(_5_on_5_DataArr[78]),Float.parseFloat(_5_on_5_DataArr[79]),
                Float.parseFloat(_5_on_5_DataArr[80]),Float.parseFloat(_5_on_5_DataArr[81]),
                Float.parseFloat(_5_on_5_DataArr[82]),Float.parseFloat(_5_on_5_DataArr[83]),
                Float.parseFloat(_5_on_5_DataArr[84]),Float.parseFloat(_5_on_5_DataArr[85]),
                Float.parseFloat(_5_on_5_DataArr[86]),Float.parseFloat(_5_on_5_DataArr[87]),
                Float.parseFloat(_5_on_5_DataArr[88]),Float.parseFloat(_5_on_5_DataArr[89]),
                Float.parseFloat(_5_on_5_DataArr[90]),Float.parseFloat(_5_on_5_DataArr[91]),
                Float.parseFloat(_5_on_5_DataArr[92]),Float.parseFloat(_5_on_5_DataArr[93]),
                Float.parseFloat(_5_on_5_DataArr[94]),Float.parseFloat(_5_on_5_DataArr[95]),
                Float.parseFloat(_5_on_5_DataArr[96]),Float.parseFloat(_5_on_5_DataArr[97]),
                Float.parseFloat(_5_on_5_DataArr[98]),Float.parseFloat(_5_on_5_DataArr[99]),
                Float.parseFloat(_5_on_5_DataArr[100]),Float.parseFloat(_5_on_5_DataArr[101]),
                Float.parseFloat(_5_on_5_DataArr[102]),Float.parseFloat(_5_on_5_DataArr[103]),
                Float.parseFloat(_5_on_5_DataArr[104]),Float.parseFloat(_5_on_5_DataArr[105]),
                Float.parseFloat(_5_on_5_DataArr[106]));

        _4_on_5_Stats=new Team4on5Stats(Integer.parseInt(_4_on_5_DataArr[6]),Float.parseFloat(_4_on_5_DataArr[7]),
                Float.parseFloat(_4_on_5_DataArr[8]),Float.parseFloat(_4_on_5_DataArr[9]),
                Float.parseFloat(_4_on_5_DataArr[10]),Float.parseFloat(_4_on_5_DataArr[11]),
                Float.parseFloat(_4_on_5_DataArr[12]),Float.parseFloat(_4_on_5_DataArr[13]),
                Float.parseFloat(_4_on_5_DataArr[14]),Float.parseFloat(_4_on_5_DataArr[15]),
                Float.parseFloat(_4_on_5_DataArr[16]),Float.parseFloat(_4_on_5_DataArr[17]),
                Float.parseFloat(_4_on_5_DataArr[18]),Float.parseFloat(_4_on_5_DataArr[19]),
                Float.parseFloat(_4_on_5_DataArr[20]),Float.parseFloat(_4_on_5_DataArr[21]),
                Float.parseFloat(_4_on_5_DataArr[22]),Float.parseFloat(_4_on_5_DataArr[23]),
                Float.parseFloat(_4_on_5_DataArr[24]),Float.parseFloat(_4_on_5_DataArr[25]),
                Float.parseFloat(_4_on_5_DataArr[26]),Float.parseFloat(_4_on_5_DataArr[27]),
                Float.parseFloat(_4_on_5_DataArr[28]),Float.parseFloat(_4_on_5_DataArr[29]),
                Float.parseFloat(_4_on_5_DataArr[30]),Float.parseFloat(_4_on_5_DataArr[31]),
                Float.parseFloat(_4_on_5_DataArr[32]),Float.parseFloat(_4_on_5_DataArr[33]),
                Float.parseFloat(_4_on_5_DataArr[34]),Float.parseFloat(_4_on_5_DataArr[35]),
                Float.parseFloat(_4_on_5_DataArr[36]),Float.parseFloat(_4_on_5_DataArr[37]),
                Float.parseFloat(_4_on_5_DataArr[38]),Float.parseFloat(_4_on_5_DataArr[39]),
                Float.parseFloat(_4_on_5_DataArr[40]),Float.parseFloat(_4_on_5_DataArr[41]),
                Float.parseFloat(_4_on_5_DataArr[42]),Float.parseFloat(_4_on_5_DataArr[43]),
                Float.parseFloat(_4_on_5_DataArr[44]),Float.parseFloat(_4_on_5_DataArr[45]),
                Float.parseFloat(_4_on_5_DataArr[46]),Float.parseFloat(_4_on_5_DataArr[47]),
                Float.parseFloat(_4_on_5_DataArr[48]),Float.parseFloat(_4_on_5_DataArr[49]),
                Float.parseFloat(_4_on_5_DataArr[50]),Float.parseFloat(_4_on_5_DataArr[51]),
                Float.parseFloat(_4_on_5_DataArr[52]),Float.parseFloat(_4_on_5_DataArr[53]),
                Float.parseFloat(_4_on_5_DataArr[54]),Float.parseFloat(_4_on_5_DataArr[55]),
                Float.parseFloat(_4_on_5_DataArr[56]),Float.parseFloat(_4_on_5_DataArr[57]),
                Float.parseFloat(_4_on_5_DataArr[58]),Float.parseFloat(_4_on_5_DataArr[59]),
                Float.parseFloat(_4_on_5_DataArr[60]),Float.parseFloat(_4_on_5_DataArr[61]),
                Float.parseFloat(_4_on_5_DataArr[62]),Float.parseFloat(_4_on_5_DataArr[63]),
                Float.parseFloat(_4_on_5_DataArr[64]),Float.parseFloat(_4_on_5_DataArr[65]),
                Float.parseFloat(_4_on_5_DataArr[66]),Float.parseFloat(_4_on_5_DataArr[67]),
                Float.parseFloat(_4_on_5_DataArr[68]),Float.parseFloat(_4_on_5_DataArr[69]),
                Float.parseFloat(_4_on_5_DataArr[70]),Float.parseFloat(_4_on_5_DataArr[71]),
                Float.parseFloat(_4_on_5_DataArr[72]),Float.parseFloat(_4_on_5_DataArr[73]),
                Float.parseFloat(_4_on_5_DataArr[74]),Float.parseFloat(_4_on_5_DataArr[75]),
                Float.parseFloat(_4_on_5_DataArr[76]),Float.parseFloat(_4_on_5_DataArr[77]),
                Float.parseFloat(_4_on_5_DataArr[78]),Float.parseFloat(_4_on_5_DataArr[79]),
                Float.parseFloat(_4_on_5_DataArr[80]),Float.parseFloat(_4_on_5_DataArr[81]),
                Float.parseFloat(_4_on_5_DataArr[82]),Float.parseFloat(_4_on_5_DataArr[83]),
                Float.parseFloat(_4_on_5_DataArr[84]),Float.parseFloat(_4_on_5_DataArr[85]),
                Float.parseFloat(_4_on_5_DataArr[86]),Float.parseFloat(_4_on_5_DataArr[87]),
                Float.parseFloat(_4_on_5_DataArr[88]),Float.parseFloat(_4_on_5_DataArr[89]),
                Float.parseFloat(_4_on_5_DataArr[90]),Float.parseFloat(_4_on_5_DataArr[91]),
                Float.parseFloat(_4_on_5_DataArr[92]),Float.parseFloat(_4_on_5_DataArr[93]),
                Float.parseFloat(_4_on_5_DataArr[94]),Float.parseFloat(_4_on_5_DataArr[95]),
                Float.parseFloat(_4_on_5_DataArr[96]),Float.parseFloat(_4_on_5_DataArr[97]),
                Float.parseFloat(_4_on_5_DataArr[98]),Float.parseFloat(_4_on_5_DataArr[99]),
                Float.parseFloat(_4_on_5_DataArr[100]),Float.parseFloat(_4_on_5_DataArr[101]),
                Float.parseFloat(_4_on_5_DataArr[102]),Float.parseFloat(_4_on_5_DataArr[103]),
                Float.parseFloat(_4_on_5_DataArr[104]),Float.parseFloat(_4_on_5_DataArr[105]),
                Float.parseFloat(_4_on_5_DataArr[106]));

        _5_on_4_Stats = new Team5on4Stats(Integer.parseInt(_5_on_4_DataArr[6]),Float.parseFloat(_5_on_4_DataArr[7]),
                Float.parseFloat(_5_on_4_DataArr[8]),Float.parseFloat(_5_on_4_DataArr[9]),
                Float.parseFloat(_5_on_4_DataArr[10]),Float.parseFloat(_5_on_4_DataArr[11]),
                Float.parseFloat(_5_on_4_DataArr[12]),Float.parseFloat(_5_on_4_DataArr[13]),
                Float.parseFloat(_5_on_4_DataArr[14]),Float.parseFloat(_5_on_4_DataArr[15]),
                Float.parseFloat(_5_on_4_DataArr[16]),Float.parseFloat(_5_on_4_DataArr[17]),
                Float.parseFloat(_5_on_4_DataArr[18]),Float.parseFloat(_5_on_4_DataArr[19]),
                Float.parseFloat(_5_on_4_DataArr[20]),Float.parseFloat(_5_on_4_DataArr[21]),
                Float.parseFloat(_5_on_4_DataArr[22]),Float.parseFloat(_5_on_4_DataArr[23]),
                Float.parseFloat(_5_on_4_DataArr[24]),Float.parseFloat(_5_on_4_DataArr[25]),
                Float.parseFloat(_5_on_4_DataArr[26]),Float.parseFloat(_5_on_4_DataArr[27]),
                Float.parseFloat(_5_on_4_DataArr[28]),Float.parseFloat(_5_on_4_DataArr[29]),
                Float.parseFloat(_5_on_4_DataArr[30]),Float.parseFloat(_5_on_4_DataArr[31]),
                Float.parseFloat(_5_on_4_DataArr[32]),Float.parseFloat(_5_on_4_DataArr[33]),
                Float.parseFloat(_5_on_4_DataArr[34]),Float.parseFloat(_5_on_4_DataArr[35]),
                Float.parseFloat(_5_on_4_DataArr[36]),Float.parseFloat(_5_on_4_DataArr[37]),
                Float.parseFloat(_5_on_4_DataArr[38]),Float.parseFloat(_5_on_4_DataArr[39]),
                Float.parseFloat(_5_on_4_DataArr[40]),Float.parseFloat(_5_on_4_DataArr[41]),
                Float.parseFloat(_5_on_4_DataArr[42]),Float.parseFloat(_5_on_4_DataArr[43]),
                Float.parseFloat(_5_on_4_DataArr[44]),Float.parseFloat(_5_on_4_DataArr[45]),
                Float.parseFloat(_5_on_4_DataArr[46]),Float.parseFloat(_5_on_4_DataArr[47]),
                Float.parseFloat(_5_on_4_DataArr[48]),Float.parseFloat(_5_on_4_DataArr[49]),
                Float.parseFloat(_5_on_4_DataArr[50]),Float.parseFloat(_5_on_4_DataArr[51]),
                Float.parseFloat(_5_on_4_DataArr[52]),Float.parseFloat(_5_on_4_DataArr[53]),
                Float.parseFloat(_5_on_4_DataArr[54]),Float.parseFloat(_5_on_4_DataArr[55]),
                Float.parseFloat(_5_on_4_DataArr[56]),Float.parseFloat(_5_on_4_DataArr[57]),
                Float.parseFloat(_5_on_4_DataArr[58]),Float.parseFloat(_5_on_4_DataArr[59]),
                Float.parseFloat(_5_on_4_DataArr[60]),Float.parseFloat(_5_on_4_DataArr[61]),
                Float.parseFloat(_5_on_4_DataArr[62]),Float.parseFloat(_5_on_4_DataArr[63]),
                Float.parseFloat(_5_on_4_DataArr[64]),Float.parseFloat(_5_on_4_DataArr[65]),
                Float.parseFloat(_5_on_4_DataArr[66]),Float.parseFloat(_5_on_4_DataArr[67]),
                Float.parseFloat(_5_on_4_DataArr[68]),Float.parseFloat(_5_on_4_DataArr[69]),
                Float.parseFloat(_5_on_4_DataArr[70]),Float.parseFloat(_5_on_4_DataArr[71]),
                Float.parseFloat(_5_on_4_DataArr[72]),Float.parseFloat(_5_on_4_DataArr[73]),
                Float.parseFloat(_5_on_4_DataArr[74]),Float.parseFloat(_5_on_4_DataArr[75]),
                Float.parseFloat(_5_on_4_DataArr[76]),Float.parseFloat(_5_on_4_DataArr[77]),
                Float.parseFloat(_5_on_4_DataArr[78]),Float.parseFloat(_5_on_4_DataArr[79]),
                Float.parseFloat(_5_on_4_DataArr[80]),Float.parseFloat(_5_on_4_DataArr[81]),
                Float.parseFloat(_5_on_4_DataArr[82]),Float.parseFloat(_5_on_4_DataArr[83]),
                Float.parseFloat(_5_on_4_DataArr[84]),Float.parseFloat(_5_on_4_DataArr[85]),
                Float.parseFloat(_5_on_4_DataArr[86]),Float.parseFloat(_5_on_4_DataArr[87]),
                Float.parseFloat(_5_on_4_DataArr[88]),Float.parseFloat(_5_on_4_DataArr[89]),
                Float.parseFloat(_5_on_4_DataArr[90]),Float.parseFloat(_5_on_4_DataArr[91]),
                Float.parseFloat(_5_on_4_DataArr[92]),Float.parseFloat(_5_on_4_DataArr[93]),
                Float.parseFloat(_5_on_4_DataArr[94]),Float.parseFloat(_5_on_4_DataArr[95]),
                Float.parseFloat(_5_on_4_DataArr[96]),Float.parseFloat(_5_on_4_DataArr[97]),
                Float.parseFloat(_5_on_4_DataArr[98]),Float.parseFloat(_5_on_4_DataArr[99]),
                Float.parseFloat(_5_on_4_DataArr[100]),Float.parseFloat(_5_on_4_DataArr[101]),
                Float.parseFloat(_5_on_4_DataArr[102]),Float.parseFloat(_5_on_4_DataArr[103]),
                Float.parseFloat(_5_on_4_DataArr[104]),Float.parseFloat(_5_on_4_DataArr[105]),
                Float.parseFloat(_5_on_4_DataArr[106]));




    }
    //GetMethods

    public String getName(){
        return this.name;
    }


    public TeamOtherStats getOtherStats() {
        return otherStats;
    }

    public TeamAllStats getAllStats() {
        return allStats;
    }

    public Team5on5Stats get_5_on_5_Stats() {
        return _5_on_5_Stats;
    }

    public Team4on5Stats get_4_on_5_Stats() {
        return _4_on_5_Stats;
    }

    public Team5on4Stats get_5_on_4_Stats() {
        return _5_on_4_Stats;
    }


}
